(function(root){'use strict';
 var doc=root.document;
 function node(tag,text,cls){var e=doc.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
 function mount(container){if(!container)return;var opened=false,page=null,mode='records',shown=100,request=null,body,status,list;
  var shell=node('div',undefined,'community-panel'),toggle=node('button','Browse community scores','button');toggle.setAttribute('aria-expanded','false');shell.appendChild(toggle);container.appendChild(shell);
  function rows(){if(!list)return;while(list.firstChild)list.removeChild(list.firstChild);var data=page?(mode==='records'?page.records:page.topScores)||[]:[];if(!data.length){list.appendChild(node('p','No scores to show.'));return;}
   for(var i=0;i<Math.min(data.length,shown);i++){var r=data[i],row=node('div',undefined,'community-row'),left=node('div',undefined,'community-player'),right=node('div',undefined,'community-score');left.appendChild(node('strong',r.scenario));left.appendChild(node('span',r.player));right.appendChild(node('strong',typeof r.score==='number'?r.score.toLocaleString(undefined,{maximumFractionDigits:2}):'—'));right.appendChild(node('span',typeof r.accuracy==='number'?r.accuracy.toFixed(1)+'% accuracy':''));row.appendChild(left);row.appendChild(right);list.appendChild(row);}
   if(data.length>shown){var more=node('button','Show more scores','button');more.onclick=function(){shown+=100;rows();};list.appendChild(more);}
  }
  function load(){if(request)return;status.textContent='Loading community scores…';var xhr=new root.XMLHttpRequest();request=xhr;xhr.open('GET','leaderboard',true);xhr.timeout=15000;xhr.onreadystatechange=function(){if(xhr.readyState!==4||request!==xhr)return;request=null;if(xhr.status!==200){status.textContent='Scores unavailable. Select Refresh to try again.';return;}try{page=JSON.parse(xhr.responseText);var stamp=new Date(page.retrievedAt);status.textContent=(page.cached?'Saved scores · ':'Updated ')+(isNaN(stamp.getTime())?'recently':stamp.toLocaleString());rows();}catch(e){status.textContent='Scores unavailable. Select Refresh to try again.';}};xhr.onerror=xhr.ontimeout=function(){if(request===xhr){request=null;status.textContent='Scores unavailable. Select Refresh to try again.';}};xhr.send();}
  toggle.onclick=function(){opened=!opened;toggle.setAttribute('aria-expanded',String(opened));if(body){body.style.display=opened?'block':'none';return;}body=node('div',undefined,'community-body');shell.appendChild(body);var toolbar=node('div',undefined,'community-toolbar'),records=node('button','Scenario records','button'),scores=node('button','Top scores','button'),refresh=node('button','Refresh','button');function choose(value){mode=value;shown=100;records.setAttribute('aria-pressed',String(mode==='records'));scores.setAttribute('aria-pressed',String(mode==='topScores'));rows();}records.onclick=function(){choose('records');};scores.onclick=function(){choose('topScores');};refresh.onclick=load;toolbar.appendChild(records);toolbar.appendChild(scores);toolbar.appendChild(refresh);body.appendChild(toolbar);status=node('p','','community-status');body.appendChild(status);list=node('div',undefined,'community-list');body.appendChild(list);choose('records');load();};
 }
 root.AimModLeaderboard={mount:mount};mount(doc.getElementById('account'));
})(window);

