const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const initial={gameEnabled:false,obsEnabled:true,opacity:.8,stats:{visible:true,x:2,y:12,width:240},versus:{visible:true,x:75,y:12,width:300}};
function setup(){
 class El{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.style={};this.clientWidth=640;this.text='';}appendChild(c){this.children.push(c);return c;}set textContent(value){this.text=value;this.children=[];}get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}setAttribute(k,v){this.attrs[k]=v;}querySelectorAll(tags){return this.children.flatMap(c=>[...(tags.split(',').includes(c.tag)?[c]:[]),...c.querySelectorAll(tags)]);}focus(){this.focused=true;}select(){this.selected=true;}}
 const requests=[],container=new El('div');
 class Xhr{constructor(){requests.push(this);this.headers={};}open(method,url){this.method=method;this.url=url;}setRequestHeader(k,v){this.headers[k]=v;}send(body){this.body=body;}abort(){this.aborted=true;}finish(status,data){this.status=status;this.responseText=JSON.stringify(data);this.readyState=4;this.onreadystatechange();}}
 const window={document:{createElement:t=>new El(t),getElementById:id=>container.querySelectorAll('button,section').find(x=>x.id===id),execCommand:()=>true},XMLHttpRequest:Xhr,location:{pathname:'/abc/ui'}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'overlay-editor.js'),'utf8'),{window});
 const api=window.AimModOverlayEditor;api.enter(container);
 const s={api,container,requests,all:tag=>container.querySelectorAll(tag),button:text=>container.querySelectorAll('button').find(b=>b.textContent===text),panel:()=>container.querySelectorAll('section').find(p=>p.style.display==='block')};
 s.ready=(value=initial)=>{requests[0].finish(200,value);requests[1].finish(200,{obsAvailable:true,obsUrl:'http://127.0.0.1:1234/abc/overlay?surface=obs'});requests[2].finish(200,{selectedKey:'',rows:[{key:'r1',name:'Example',score:120,scenario:'Practice'}]});};
 return s;
}
test('tabs show one compact panel and survive resize',()=>{const s=setup();s.ready();assert.equal(s.panel().id,'overlay-panel-setup');for(const [tab,id]of [['Layout','layout'],['VS','vs'],['OBS','obs'],['Setup','setup']]){s.button(tab).onclick();assert.equal(s.panel().id,'overlay-panel-'+id);assert.equal(s.all('section').filter(p=>p.style.display==='block').length,1);s.api.resize();assert.equal(s.panel().id,'overlay-panel-'+id);assert.equal(s.button(tab).attrs['aria-selected'],'true');}});
test('tab keyboard navigation moves selection and focus',()=>{const s=setup();s.ready();let prevented=false;s.button('Setup').onkeydown({keyCode:39,preventDefault(){prevented=true;}});assert.ok(prevented);assert.equal(s.panel().id,'overlay-panel-layout');assert.ok(s.button('Layout').focused);s.button('Layout').onkeydown({keyCode:35,preventDefault(){}});assert.equal(s.panel().id,'overlay-panel-obs');});
test('layout saves preserve active tab and failed saves keep original values',()=>{const s=setup();s.ready();s.button('Layout').onclick();const inputs=s.panel().querySelectorAll('input');inputs[0].value='9';inputs[0].onchange();assert.deepEqual(JSON.parse(s.requests[3].body),{stats:{x:9}});assert.equal(s.requests[3].headers['X-AimMod-UI'],'1');assert.ok(s.button('Layout').disabled);s.requests[3].finish(503,{});assert.equal(s.panel().id,'overlay-panel-layout');assert.equal(s.panel().querySelectorAll('input')[0].value,'2');assert.match(s.container.textContent,/Could not save/);});
test('setup toggles, layout reset and opacity retain original settings API',()=>{const s=setup();s.ready();s.all('button').find(b=>b.attrs['aria-label']==='In-game HUD').onclick();assert.deepEqual(JSON.parse(s.requests[3].body),{gameEnabled:true});s.requests[3].finish(200,{...initial,gameEnabled:true});s.button('Layout').onclick();const opacity=s.panel().querySelectorAll('input')[6];opacity.value='55';opacity.onchange();assert.deepEqual(JSON.parse(s.requests[4].body),{opacity:.55});s.requests[4].finish(200,initial);s.button('Reset positions').onclick();assert.deepEqual(JSON.parse(s.requests[5].body),{stats:{x:1,y:100,width:560},versus:{x:100,y:100,width:300}});});
test('VS selection and OBS copy remain reachable',()=>{const s=setup();s.ready();s.button('VS').onclick();const selector=s.panel().querySelectorAll('select')[0];selector.value='r1';selector.onchange();assert.deepEqual(JSON.parse(s.requests[3].body),{key:'r1'});s.requests[3].finish(200,{selectedKey:'r1',rows:[]});assert.equal(s.panel().id,'overlay-panel-vs');s.button('OBS').onclick();s.button('Copy browser-source URL').onclick();assert.match(s.panel().textContent,/Copied/);assert.ok(s.panel().querySelectorAll('input')[0].selected);});
test('leaving aborts requests and late responses cannot rerender',()=>{const s=setup();s.api.leave();const before=s.container.textContent;s.requests[0].finish(200,initial);assert.equal(s.container.textContent,before);assert.ok(s.requests.every(r=>r.aborted));});

test('OBS layout editing changes only OBS settings and preserves surface selection',()=>{
 const s=setup();const obs={opacity:.4,stats:{...initial.stats,x:88},versus:{...initial.versus,visible:false}};s.ready({...initial,obs,layouts:[]});s.button('Layout').onclick();s.button('OBS layout').onclick();
 const x=s.panel().querySelectorAll('input')[0];assert.equal(x.value,'88');x.value='77';x.onchange();assert.deepEqual(JSON.parse(s.requests[3].body),{obs:{stats:{x:77}}});
 s.requests[3].finish(200,{...initial,obs:{...obs,stats:{...obs.stats,x:77}},layouts:[]});assert.equal(s.button('OBS layout').attrs['aria-pressed'],'true');s.button('Game layout').onclick();assert.equal(s.panel().querySelectorAll('input')[0].value,'2');
});
test('named layouts save chosen surface, apply by name and require explicit delete',()=>{
 const s=setup();s.ready({...initial,obs:{opacity:.4,stats:initial.stats,versus:initial.versus},layouts:[]});s.button('Layout').onclick();
 const name=s.panel().querySelectorAll('input').find(x=>x.attrs['aria-label']==='Layout name');name.value='Practice';s.button('Save layout').onclick();assert.deepEqual(JSON.parse(s.requests[3].body),{layoutAction:'save',name:'Practice',surface:'game'});
 s.requests[3].finish(200,{...initial,layouts:[{name:'Practice',layout:{opacity:.8,stats:initial.stats,versus:initial.versus}}]});s.button('OBS layout').onclick();s.button('Apply layout').onclick();assert.deepEqual(JSON.parse(s.requests[4].body),{layoutAction:'apply',name:'Practice',surface:'obs'});
 s.requests[4].finish(200,{...initial,layouts:[{name:'Practice'}]});s.button('Delete layout').onclick();assert.equal(s.requests.length,5);s.button('Confirm delete').onclick();assert.deepEqual(JSON.parse(s.requests[5].body),{layoutAction:'delete',name:'Practice',surface:'obs'});
});
