(function(root){
 'use strict';var container=null,generation=0,pending=[],settings=null,setup=null,opponents=null,busy=false,activeTab='setup',status='',layoutSurface='game',selectedLayout='';
 function el(tag,text,css){var n=root.document.createElement(tag);if(text!==undefined)n.textContent=text;if(css)n.className=css;return n;}
 function leave(){generation++;pending.forEach(function(x){x.abort();});pending=[];container=null;busy=false;}
 function request(path,body,done){var ticket=generation,x=new root.XMLHttpRequest();pending.push(x);var base=root.location.pathname;base=base.slice(0,base.lastIndexOf('/'));x.open(body?'POST':'GET',base+'/'+path,true);x.timeout=12000;if(body){x.setRequestHeader('X-AimMod-UI','1');x.setRequestHeader('Content-Type','application/json');}var finished=false;function finish(ok,data){if(finished)return;finished=true;if(ticket!==generation||!container)return;pending=pending.filter(function(y){return y!==x;});done(ok,data);}x.onreadystatechange=function(){if(x.readyState!==4)return;try{finish(x.status===200,JSON.parse(x.responseText));}catch(e){finish(false,null);}};x.onerror=x.ontimeout=function(){finish(false,null);};x.send(body?JSON.stringify(body):null);}
 function save(patch){if(busy)return;busy=true;var controls=container.querySelectorAll('button,input,select');for(var i=0;i<controls.length;i++)controls[i].disabled=true;request('overlay-settings',patch,function(ok,data){busy=false;if(ok)settings=data;render(ok?'Saved.':'Could not save. Please try again.');});}
 function surfaceLayout(){return layoutSurface==='obs'?(settings.obs||settings):settings;}
 function saveLayout(patch){save(layoutSurface==='obs'?{obs:patch}:patch);}
 function button(label,callback,primary){var b=el('button',label,'button'+(primary?' primary':''));b.type='button';b.onclick=function(){if(!busy)callback();};return b;}
 function actions(parent){var r=el('div',undefined,'actions');parent.appendChild(r);return r;}
 function visibility(on,title,callback){var wrap=el('span',undefined,'overlay-visibility'),b=button(on?'Visible':'Hidden',callback,on);b.className='switch'+(on?' on':'');b.appendChild(el('span',undefined,'knob'));b.setAttribute('role','switch');b.setAttribute('aria-checked',String(on));b.setAttribute('aria-label',title);wrap.appendChild(b);wrap.appendChild(el('span',on?'Shown':'Hidden','switch-state'));return wrap;}
 function toggle(parent,key,title,description){var row=el('div',undefined,'overlay-setting-row'),copy=el('div');copy.appendChild(el('h3',title));copy.appendChild(el('p',description,'subtle'));row.appendChild(copy);var b=button(settings[key]?'On':'Off',function(){var p={};p[key]=!settings[key];save(p);},settings[key]);b.className='switch'+(settings[key]?' on':'');b.appendChild(el('span',undefined,'knob'));b.setAttribute('role','switch');b.setAttribute('aria-checked',String(settings[key]));b.setAttribute('aria-label',title);row.appendChild(el('span',settings[key]?'On':'Off','switch-state'));row.appendChild(b);parent.appendChild(row);}
 function focusedId(){var active=root.document.activeElement;return active&&active.id&&active.id.indexOf('overlay-')===0?active.id:'';}
 function restoreFocus(id){if(!id||!root.document.getElementById)return;var target=root.document.getElementById(id);if(target&&target.focus&&!target.disabled)target.focus();}
 // Saving rebuilds the editor; keep keyboard focus on the same control.
 function render(message){var focus=focusedId();draw(message);restoreFocus(focus);}
 function draw(message){if(!container)return;if(message!==undefined)status=message;container.textContent='';if(!settings){if(!message){container.appendChild(el('div',undefined,'panel overlay-editor-panel')).appendChild(el('p','Loading overlay settings…','subtle'));return;}var failed=el('div',undefined,'panel empty');failed.appendChild(el('h3','Could not load overlay settings'));failed.appendChild(el('p','AimMod couldn’t reach its local service. Your overlays keep their last saved layout.'));actions(failed).appendChild(button('Try again',function(){render();load();},true));container.appendChild(failed);return;}
  var tabs=el('div',undefined,'overlay-editor-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Overlay settings');[['setup','Setup'],['layout','Layout'],['vs','VS'],['obs','OBS']].forEach(function(tab,index){var b=button(tab[1],function(){activeTab=tab[0];status='';render();});b.className='overlay-editor-tab'+(activeTab===tab[0]?' active':'');b.id='overlay-tab-'+tab[0];b.setAttribute('role','tab');b.setAttribute('aria-selected',String(activeTab===tab[0]));b.setAttribute('aria-controls','overlay-panel-'+tab[0]);b.tabIndex=activeTab===tab[0]?0:-1;b.onkeydown=function(event){var code=event.keyCode;if(code!==37&&code!==39&&code!==36&&code!==35)return;event.preventDefault();var next=code===36?0:code===35?3:(index+(code===39?1:3))%4;activeTab=['setup','layout','vs','obs'][next];render();var target=root.document.getElementById('overlay-tab-'+activeTab);if(target)target.focus();};tabs.appendChild(b);});container.appendChild(tabs);if(status){var notice=el('p',status,'overlay-save-status');notice.setAttribute('role','status');container.appendChild(notice);}function section(key){var n=el('section',undefined,'panel overlay-editor-panel');n.id='overlay-panel-'+key;n.setAttribute('role','tabpanel');n.setAttribute('aria-labelledby','overlay-tab-'+key);n.style.display=activeTab===key?'block':'none';return n;}
  var surfaces=section('setup');surfaces.appendChild(el('h2','Live overlays'));surfaces.appendChild(el('p','Choose where your live stats and VS comparison appear.','subtle'));toggle(surfaces,'gameEnabled','In-game HUD','Show during normal runs. Hidden in menus and replays.');toggle(surfaces,'obsEnabled','OBS browser source','Share live stats through a transparent browser source.');container.appendChild(surfaces);
  var layout=section('layout');layout.appendChild(el('h2','HUD layout'));layout.appendChild(el('p','Position each surface independently. Positions are percentages of its screen.','subtle'));var surfaceTabs=el('div',undefined,'overlay-surface-tabs segmented');['game','obs'].forEach(function(surface){var b=button(surface==='game'?'Game layout':'OBS layout',function(){layoutSurface=surface;render();},layoutSurface===surface);b.setAttribute('aria-pressed',String(layoutSurface===surface));surfaceTabs.appendChild(b);});var surfaceRow=el('div',undefined,'actions overlay-surface-row');surfaceRow.appendChild(surfaceTabs);layout.appendChild(surfaceRow);var layoutBody=el('div',undefined,'overlay-layout-body'),controls=el('div',undefined,'overlay-layout-controls'),visual=el('div',undefined,'overlay-layout-visual');layoutBody.appendChild(controls);layoutBody.appendChild(visual);layout.appendChild(layoutBody);visual.appendChild(el('h3','Preview'));visual.appendChild(el('p','Where each card sits on a 16:9 screen.','subtle'));var currentLayout=surfaceLayout();
  ['stats','versus'].forEach(function(key){var placement=currentLayout[key],group=el('div',undefined,'overlay-layout-group'),groupHead=group.appendChild(el('div',undefined,'overlay-layout-head'));groupHead.appendChild(el('h3',key==='stats'?'Live stats':'VS mode'));groupHead.appendChild(visibility(placement.visible,key==='stats'?'Show live stats':'Show VS mode',function(){var p={};p[key]={visible:!placement.visible};saveLayout(p);},placement.visible));[['x','Horizontal position (%)',0,100],['y','Vertical position (%)',0,100],['width','Width (px)',140,600]].forEach(function(field){var label=el('label',undefined,'overlay-number');label.appendChild(el('span',field[1]));var input=el('input');input.id='overlay-field-'+key+'-'+field[0];input.type='number';input.min=String(field[2]);input.max=String(field[3]);input.step='1';input.value=String(placement[field[0]]);input.onchange=function(){var v=Number(input.value);if(!isFinite(v)||v<field[2]||v>field[3]){input.value=String(placement[field[0]]);return;}var p={};p[key]={};p[key][field[0]]=v;saveLayout(p);};label.appendChild(input);group.appendChild(label);});controls.appendChild(group);});
  var opacityLabel=el('label',undefined,'overlay-number');opacityLabel.appendChild(el('span','Opacity (%)'));var opacity=el('input');opacity.id='overlay-field-opacity';opacity.type='number';opacity.min='0';opacity.max='100';opacity.value=String(Math.round(currentLayout.opacity*100));opacity.onchange=function(){var value=Number(opacity.value);if(isFinite(value)&&value>=0&&value<=100)saveLayout({opacity:value/100});else opacity.value=String(Math.round(currentLayout.opacity*100));};opacityLabel.appendChild(opacity);var inline=el('div',undefined,'overlay-inline-row');inline.appendChild(opacityLabel);inline.appendChild(button('Reset positions',function(){saveLayout({stats:{x:1,y:100,width:560},versus:{x:100,y:100,width:300}});}));controls.appendChild(inline);
  var preview=el('div',undefined,'overlay-layout-preview');preview.setAttribute('aria-label','Overlay layout preview');visual.appendChild(preview);container.appendChild(layout);var w=preview.offsetWidth||preview.clientWidth||640,h=Math.round(w*9/16);preview.style.height=h+'px';var sky=el('div',undefined,'overlay-preview-sky'),floor=el('div',undefined,'overlay-preview-floor');sky.style.height=Math.round(h*0.55)+'px';floor.style.top=Math.round(h*0.55)+'px';floor.style.height=(h-Math.round(h*0.55))+'px';preview.appendChild(sky);preview.appendChild(floor);['stats','versus'].forEach(function(key){var p=currentLayout[key];if(!p.visible)return;var card=el('div',key==='stats'?'Live stats':'VS mode','overlay-preview-card');var cw=Math.max(72,p.width*w/1920),ch=Math.max(26,Math.round((key==='stats'?150:120)*h/1080));card.style.height=ch+'px';card.style.lineHeight=(ch-2)+'px';card.style.width=cw+'px';card.style.left=Math.max(0,Math.min(w-cw,w*p.x/100))+'px';card.style.top=Math.max(0,Math.min(h-ch,h*p.y/100))+'px';card.style.opacity=String(currentLayout.opacity);preview.appendChild(card);});
  var saved=el('div',undefined,'overlay-saved-layouts');saved.appendChild(el('h3','Saved layouts'));var picker=el('select');picker.setAttribute('aria-label','Saved layout');var blank=el('option','Choose a layout');blank.value='';picker.appendChild(blank);(settings.layouts||[]).forEach(function(entry){var option=el('option',entry.name);option.value=entry.name;picker.appendChild(option);});picker.value=selectedLayout;picker.onchange=function(){if(busy)return;selectedLayout=picker.value;render();};var pickField=el('label',undefined,'overlay-saved-field');pickField.appendChild(el('span','Saved layout'));pickField.appendChild(picker);saved.appendChild(pickField);var name=el('input');name.type='text';name.maxLength=48;name.value=selectedLayout;name.setAttribute('aria-label','Layout name');var nameField=el('label',undefined,'overlay-saved-field');nameField.appendChild(el('span','Layout name'));nameField.appendChild(root.AimModFormat&&root.AimModFormat.field?root.AimModFormat.field(name,'For example: Stream'):name);saved.appendChild(nameField);saved.appendChild(button('Save layout',function(){var value=name.value.trim();if(!value){name.focus();return;}selectedLayout=value;save({layoutAction:'save',name:value,surface:layoutSurface});}));if(selectedLayout&&(settings.layouts||[]).some(function(entry){return entry.name===selectedLayout;})){saved.appendChild(button('Apply layout',function(){save({layoutAction:'apply',name:selectedLayout,surface:layoutSurface});}));var remove=button('Delete layout',function(){remove.textContent='Confirm delete';remove.onclick=function(){if(busy)return;var previous=selectedLayout;selectedLayout='';save({layoutAction:'delete',name:previous,surface:layoutSurface});};});saved.appendChild(remove);}controls.appendChild(saved);
  var vs=section('vs');vs.appendChild(el('h2','VS opponent'));var chooser=el('select');chooser.id='overlay-opponent';chooser.setAttribute('aria-label','VS opponent');var own=el('option','Personal best');own.value='';chooser.appendChild(own);var selected=opponents&&opponents.selectedKey||'',found=!selected;(opponents&&opponents.rows||[]).forEach(function(row){var option=el('option',(row.name||'Unknown player')+' · '+(root.AimModFormat?root.AimModFormat.number(row.score):String(row.score))+' · '+(row.scenario||'Unknown scenario'));option.value=row.key;chooser.appendChild(option);if(row.key===selected)found=true;});if(!found){var missing=el('option','Selected opponent unavailable');missing.value=selected;chooser.appendChild(missing);}chooser.value=selected;chooser.onchange=function(){if(busy)return;busy=true;chooser.disabled=true;request('overlay-opponents',{key:chooser.value},function(ok,data){busy=false;if(ok)opponents=data;render(ok?'Opponent saved.':'Could not select this opponent. Refresh and try again.');});};vs.appendChild(chooser);vs.appendChild(el('p','Opponent scores come from the game’s loaded leaderboard. Open a scenario’s leaderboard to make its players available here.','subtle'));actions(vs).appendChild(button('Refresh opponents',function(){request('overlay-opponents',null,function(ok,data){if(ok)opponents=data;render(ok?'':'Could not refresh opponents.');});}));container.appendChild(vs);
  var obs=section('obs');obs.appendChild(el('h2','Add to OBS'));obs.appendChild(el('p','Add a Browser source in OBS, paste this URL, and set its size to 1920 × 1080. The background is transparent.','subtle'));if(setup&&setup.obsAvailable){var url=el('input');url.type='text';url.readOnly=true;url.value=setup.obsUrl;url.setAttribute('aria-label','OBS browser source URL');url.className='overlay-source-url';obs.appendChild(url);obs.appendChild(el('p','Keep this URL private. It gives access to your live stats on this PC while AimMod runs.','subtle overlay-url-note'));var feedback=el('p','','subtle');actions(obs).appendChild(button('Copy browser-source URL',function(){url.focus();url.select();var copied=false;try{copied=root.document.execCommand('copy');}catch(e){}feedback.textContent=copied?'Copied.':'URL selected. Press Ctrl+C to copy.';}));obs.appendChild(feedback);}else obs.appendChild(el('p','The browser source is unavailable. Restart AimMod to retry.','subtle'));container.appendChild(obs);
 }
 function load(){request('overlay-settings',null,function(ok,data){if(ok)settings=data;render(ok?'':'Could not load overlay settings.');});request('overlay-setup',null,function(ok,data){if(ok)setup=data;if(settings)render();});request('overlay-opponents',null,function(ok,data){if(ok)opponents=data;if(settings)render();});}
 root.AimModOverlayEditor={enter:function(target){leave();container=target;activeTab='setup';status='';settings=null;setup=null;opponents=null;if(container){render();load();}},leave:leave,resize:function(){if(container&&settings&&!busy)render();}};
})(window);
